### ISSUE TITLE
Code is not modular 

### ISSUE THREAD

**Issue by TheSpiderPig** [lnkit/ACID.JS#2]
over 2500 lines of code in one file. 

Consider breaking up the code into smaller pieces. 
Use browserfy or some other tools (requirejs?) for compiling the source code together. 

introduce a build system to automate the process of combining aspects of your project. (Grunt or Gulp)

**Comment by lnkit** [comment]
LNKit is currently completely modularized. The only large file is the main library with spaces and comments sits at 2500 lines. Compressed it's 35565 bytes where as jquery is 84320. Requirejs and browserfy would only increase the size. The entire platform is based on a modular design please refer to the .ensure and .import function which is similar to including requirejs and browserfy however it's smaller faster and much lighter.

**Comment by lnkit** [comment]
For information on DOCS refer to https://lnkit.com/acidjs/ Keep in mind the docs and the library are still under heavy and active development.

**Comment by lnkit** [comment]
New structure will be up using gulp by the end of tonight. Working example is already on beta version.
